server:
  port: 8090

spring:
  application:
    name: smart-parking
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://sql.lvning.club:3306/smart-parking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: lvning
    password: Lvning107754
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

